"""Added Event model

Revision ID: 290a10a41e70
Revises: 4fa57225fe68
Create Date: 2023-11-07 19:07:29.407716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290a10a41e70'
down_revision = '4fa57225fe68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.Time(), nullable=False))
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.drop_column('time')

    # ### end Alembic commands ###
