"""Added Event model

Revision ID: 5d1b8414b106
Revises: d8357b4fecbf
Create Date: 2023-11-07 11:43:45.445274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d1b8414b106'
down_revision = 'd8357b4fecbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('duration', sa.String(length=20), nullable=False))
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('location_address')
        batch_op.drop_column('location_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_name', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('location_address', sa.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.DATETIME(), nullable=False))
        batch_op.drop_column('duration')
        batch_op.drop_column('time')

    # ### end Alembic commands ###
